[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://word-adventure-kids-dashboard-production.up.railway.app/api"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://word-adventure-kids-dashboard-production.up.railway.app/api"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://word-adventure-kids-dashboard-production.up.railway.app/api"
